import Head from 'next/head'
import Navbar from '../components/Navbar'
import HeroSection from '../components/HeroSection'
import Footer from '../components/Footer'
import TermsHeroSection from '../components/HeroSection/terms';

export default function Home() {
  return (
    <>
      <Head>
        <title>Big Yellow Box</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <Navbar />
      <TermsHeroSection />
      <Footer />
    </>
  );
}
